services:
  functional-chatbots:
    build: .
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:${PORT:-8000}"
    volumes:
      - .:/code
    ports:
      - "${PORT:-8000}:${PORT:-8000}"
