#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

# Common
# --------------------------------------------------
python manage.py migrate --noinput
python manage.py collectstatic --noinput --clear --ignore=input.css

if [ "$ENVIRONMENT" = "local" ]; then
    echo "Running in local development mode"
    exec python manage.py runserver 0.0.0.0:8000

elif [ "$ENVIRONMENT" = "production" ]; then
    echo "Running in production mode"
    exec granian --interface wsgi --host 0.0.0.0 --port 8000 --workers 2 config.wsgi:application
fi
