# Generated by Django 6.0.6 on 2026-06-07 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('cheese', 'Cheese'), ('pepperoni', 'Pepperoni'), ('vegetarian', 'Vegetarian')], max_length=50)),
                ('size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_time', models.IntegerField(default=60)),
            ],
        ),
    ]
