# Generated by Django 6.0.6 on 2026-06-09 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizzaorder',
            name='session_key',
            field=models.CharField(db_index=True, default='', max_length=40),
        ),
    ]
