# Generated by Django 5.0.6 on 2024-06-04 02:41

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PizzaOrder",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("cheese", "Cheese"),
                            ("pepperoni", "Pepperoni"),
                            ("vegetarian", "Vegetarian"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("small", "Small"),
                            ("medium", "Medium"),
                            ("large", "Large"),
                        ],
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("total_time", models.IntegerField(default=60)),
            ],
        ),
    ]
