# Generated by Django 5.0.8 on 2024-08-07 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizzaorder',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
